### PR TITLE
Enrich expression API

### PR DESCRIPTION
**Pull request by mitikov**
Adding primitive APIs to reduce the volume of boilerplate code to be written while working with expressions.

Inspired by #70

### CODE REVIEW

**Comment by mitikov** [comment]
@arnaudleclerc Could you please review?

Thanks.

**Comment by arnaudleclerc** [comment]
@mitikov Thanks for the PR, this is a great improvement! Everything looks fine.

Do you think it is possible to add some unit tests on the new code ?

**Comment by mitikov** [comment]
@arnaudleclerc Sure, here you go :)

**Comment by arnaudleclerc** [comment]
Awesome, thank you!

**Pull request merged**
